apiVersion: v1
kind: Service
metadata:
  name: vllm-ui
  namespace: default
  labels: 
    prometheus: enabled
spec:
  selector:
    app: vllm-ui
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP

