# dcgm-servicemonitor.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: dcgm-exporter
  namespace: monitoring
spec:
  namespaceSelector:
    matchnames:
      - default
  selector:
    matchLabels:
      app: nvidia-dcgm-exporter
  endpoints:
    - ports: gpu-metrics
      path: /metrics
      interval: 15s
      scheme: http
