apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: dcgm-exporter
  namespace: default
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: nvidia-dcgm-exporter     # <-- changed to match your Service
  namespaceSelector:
    matchNames: [default]
  endpoints:
    - port: gpu-metrics             # your Service port name
      interval: 15s
