{
 "title": "GPU-Dash",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "SM_Clock-Frequency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "DCGM_FI_DEV_SM_CLOCK", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "GPU_Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    { "expr": "DCGM_FI_DEV_GPU_TEMP", "legendFormat": "{{UUID}}" }
   ]
  },
  {
   "title": "Free-memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    { "expr": "DCGM_FI_DEV_FB_FREE", "legendFormat": "{{Hostname}}" }
   ]
  },
  {
   "title": "GPU Utilizaton",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "DCGM_FI_DEV_GPU_UTIL", "legendFormat": "{{Hostname}}" }
   ]
  },
  {
   "title": "Memory-Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    { "expr": "DCGM_FI_DEV_FB_USED", "legendFormat": "{{Hostname}}" }
   ]
  }
 ]
}