apiVersion: v1
kind: Service
metadata:
  name: inference-router
  labels:
    prometheus: enabled    
spec:
  selector:
    app: inference-router
  ports:
    - name: http
      port: 9090
      targetPort: 9090
      protocol: TCP
